### PR TITLE
Fixed portal redirect to local

### LINKED ISSUE #1946: Routing type portal has no redirect to local
Webspace Url: sulu.lo/{loca..}

I added a custom route with type: portal `/event/{id}``

Now I can visit `/event/1` and `/de/event/1`.

The request analyzer should redirect the `/event/1` to `/de/event/1` same as for content pages.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | yes
| Fixed tickets | fixes #1946 
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes the `PortalRouteLoader` to generate redirects for partial matched Portals. If you register your custom-routes they will be generated for each Portal.

For example the website_search in the sulu-standard:

```yml
website_search:
    pattern: /search
    defaults:
        _controller: "ClientWebsiteBundle:Search:query"
```

Generates routes for `sulu.lo/de/search` and `sulu.lo/en/search` and also for `sulu.lo/search`. The last should redirect to /en/search (en is the default locale) because sulu-pages has the same behaviour.

#### BC Breaks/Deprecations

In this PR i have deprecated the functions: 

* SuluWebsiteBundle:Default:redirect
* SuluWebsiteBundle:Default:redirectWebspaceAction

They still exists and sitll working because they forward to the new Controller `SuluWebsiteBundle:Redirect` which contains now all the redirect functions for sulu.

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@chirimoya should i add a message into the UPGRADE.md because of the deprecations or is a deprecation message enough?

**Comment by wachterjohannes** [comment]
we have decided not to add deprecations to the upgrade to keep it simple and compact.

**Comment by patkar** [comment]
> we have decided not to add deprecations to the upgrade to keep it simple and compact.
eeek, then I should update the docs again ^^

**Comment by wachterjohannes** [comment]
@patkar why? is it defined there?

**Comment by patkar** [comment]
Yep, https://github.com/sulu-io/sulu-docs/pull/180/files#diff-dda7cd6ab5985199df16017f5dc51ce2R80

**Comment by wachterjohannes** [comment]
hmm then maybe reintroduce the discussion /cc @chirimoya @danrot

**Comment by danrot** [comment]
Then we probably have to update the docs again, I don't think that this is a valid argument in a discussion :wink:

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php [hunk 1]
```diff
@@ -45,89 +44,41 @@ public function indexAction(StructureInterface $structure, $preview = false, $pa
...
     public function redirectWebspaceAction(Request $request)
     {
-        $url = $this->resolveRedirectUrl(
-            $request->get('redirect'),
-            $request->getUri()
-        );
+        @trigger_error('SuluWebsiteBundle:Default:redirectWebspace is deprecated since version 1.2. Use the "SuluWebsiteBundle:Redirect:redirectWebspace" action instead.', E_USER_DEPRECATED);
 
-        return new RedirectResponse($url, 301);
+        return $this->forward(
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: Doesn't this cause another redirect or sub request? Shouldn't we simply call the other controller here?

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php [hunk 2]
```diff
@@ -45,89 +44,41 @@ public function indexAction(StructureInterface $structure, $preview = false, $pa
...
-            $url = 'http://' . $url;
-        }
+        @trigger_error('SuluWebsiteBundle:Default:redirect is deprecated since version 1.2. Use the "SuluWebsiteBundle:Redirect:redirect" action instead.', E_USER_DEPRECATED);
 
-        return parse_url($url);
+        return $this->forward(
+            'SuluWebsiteBundle:Redirect:redirect',
+            $request->attributes->all(),
+            $request->query->all()
+        );
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: Same as above

File: src/Sulu/Bundle/WebsiteBundle/Controller/RedirectController.php [hunk 3]
```diff
@@ -0,0 +1,143 @@
...
+     * @param Request $request
+     * @param string $route
+     * @param bool $permanent
+     *
+     * @return RedirectResponse
+     */
+    public function redirectToRouteAction(Request $request, $route, $permanent = false)
+    {
+        if ('' === $route) {
+            throw new HttpException($permanent ? 410 : 404);
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Controller/RedirectController.php]: I think 410 is not a good idea here. Indicates that there was a resource, but is not anymore, which is not the case here. Why do you want to differentiate at all?

Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Controller/RedirectController.php]: i have copied the logic from symfony `RedirectController` https://github.com/symfony/symfony/blob/f29d46f29b/src/Symfony/Bundle/FrameworkBundle/Controller/RedirectController.php#L49

File: src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php (hunk 1 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: yes it creates a subrequest. but we cannot call the other controller directly because its not a service. Otherwise we have to use the `ControllerReolver` which is a very deep functionality of symfony which should not really be used directly (i think)

Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: I would still prefer it. Don't you think that this can cause unexpected behavior, when thinking about caching and other stuff. Apart from that it is only a workaround to keep the deprecation working, so I don't think it is so bad, but at the same time I don't care about it too much.

Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Controller/DefaultController.php]: like i said i wouldn't add more complexity here and use the functionality of the symfony controller. sometimes this will be deleted and all which uses this should change it to the newer version.
