### PR TITLE
Fixed block type don't triggers save-button

### LINKED ISSUE #1965: Switching block type does not enable save-button
In the page edit view of the admin interface, switching the block type of a section does not enable the save button. Another field needs to be changed (e.g. adding and removing a letter in a text field) in order to activate the save button.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #1965 
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes an issue with the block-content type. This happens for example if you open a page with the example template and change the block type (or adding / deleting block)

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js [hunk 1]
```diff
@@ -309,6 +309,9 @@ define(['app-config', 'config', 'sulucontent/components/content/preview/main'],
                     // ignore exceptions
                 }
 
+                // enable save button
+                this.setHeaderBar(false);
```
Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content/form/main.js]: will also be triggered when changing the block type
