### PR TITLE
fixed canonical tag for shadow pages

### LINKED ISSUE #1533: Hreflang tag is not valid for specific country languages
Wrong
```
hreflang="de_at"
```

Correct
```
hreflang="de-at"
```

https://support.google.com/webmasters/answer/189077?hl=de

### PR DESCRIPTION
**Pull request by danrot**
Fixes the canonical tag issue for shadow pages in a new twig extension. Also fixes #1533.

__tasks:__

- [x] test coverage
- [x] gather feedback for my changes
- [ ] submit changes to the documentation

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1533 
| BC breaks        | `sulu_meta_seo` twig method is now deprecated, use `sulu_seo` instead
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/70

### CODE REVIEW

**Comment by danrot** [comment]
@chirimoya Can you do the technical review?
@c00n84 Can you test if all your cases are working now?

File: src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php [hunk 1]
```diff
@@ -0,0 +1,233 @@
...
+     * @param array $seoExtension The values delivered by the SEO extension of Sulu
+     * @param string[] $urls All the localized URLs for the current page
+     * @param string $shadowBaseLocale The displayed language, in case the current page is a shadow
+     * @param string $webspaceKey The key of the current webspace
+     *
+     * @return string The rendered canonical link tag
+     */
+    private function renderCanonicalTag(array $seoExtension, array $urls, $shadowBaseLocale, $webspaceKey)
+    {
+        $canonicalTagHtml = '<link rel="canonical" href="%s"/>';
```
Comment (chirimoya) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php]: `PHP_EOL`

**Comment by chirimoya** [comment]
else ACK
