### PR TITLE
Fixed url-field to provide URL-scheme

### LINKED ISSUE #1318: Allow protocol selection for URL content type
Currently, URLs are fixed to the HTTP protocol, not allowing HTTPS URLs to be specified.

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes
- [x] submit changes to the documentation
- [x] URL-input in husky (https://github.com/massiveart/husky/pull/562)
- [x] URL-input in sulu
- [x] preview
- [x] config
  * default scheme and specificPart
  * schemes
- [x] fix prefixes on multiple places in sulu
- [x] contact form
- [x] account form
- [x] upgrade contact
- [x] upgrade account
- [x] upgrade content
- [x] upgrade snippets

__Related PRs:__

* https://github.com/massiveart/husky/pull/562
* https://github.com/sulu-io/sulu-standard/pull/527
* https://github.com/sulu-io/sulu-docs/pull/122

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1318 
| BC breaks        | see upgrade.md
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/122

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201508081500.php [hunk 1]
```diff
@@ -0,0 +1,242 @@
...
+use Sulu\Component\Content\Metadata\Factory\StructureMetadataFactoryInterface;
+use Sulu\Component\Content\Metadata\PropertyMetadata;
+use Sulu\Component\Content\Metadata\StructureMetadata;
+use Sulu\Component\DocumentManager\PropertyEncoder;
+use Sulu\Component\PHPCR\SessionManager\SessionManagerInterface;
+use Sulu\Component\Webspace\Manager\WebspaceManagerInterface;
+use Symfony\Component\DependencyInjection\ContainerAwareInterface;
+use Symfony\Component\DependencyInjection\ContainerInterface;
+
+class Version201508081500 implements VersionInterface, ContainerAwareInterface
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201508081500.php]: Can you add a PHPDoc? Hard to get a quick idea of what this migration is doing without it.

File: src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201508081500.php [hunk 2]
```diff
@@ -0,0 +1,242 @@
...
+                $callback($node, $name);
+            }
+        }
+    }
+
+    /**
+     * @param string $locale
+     * @param callable $callback
+     */
+    private function iterateExternalLink($locale, $callback)
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/phpcr-migrations/Version201508081500.php]: callable hint missing

File: src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/url.html.twig [hunk 3]
```diff
@@ -1,13 +1,16 @@
...
-     data-type="husky-input"
+     data-aura-input-class="no-preview-update"
+     data-aura-scheme="{{ params.defaults.value.scheme.value | default('http://') }}"
+     data-aura-specific-part="{{ params.defaults.value.specific_part.value | default('') }}"
+     data-aura-schemes="{{ sulu_parameter_to_names_array(params.schemes.value) | json_encode }}"
+     data-type="url-input"
+     data-type-schemes="{{ sulu_parameter_to_names_array(params.schemes.value) | json_encode }}"
      data-form="true"
-     class="preview-update trigger-save-button"
+     class="preview-change-update trigger-save-button"
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/url.html.twig]: Was this an error before?

Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/url.html.twig]: no net really but the structure of this content-type has changed and so i have to define a new way to update the preview over the dom change event.

Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/url.html.twig]: I don't really get that :-)

Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/url.html.twig]: with this class the preview hears on the dom change event to detect changed data. this event is new and introduced to decouple content type from preview. the content type only throws the dom event "change" when the data was changed. i will document that when we write the chapter "how to implement custom content types".

Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/views/Template/content-types/url.html.twig]: Ok, now I get it... maybe we should an issue targeted at 2.0, which will replace the `preview-update` with the `preview-change-update` class, so that we handle all of this stuff the same.

**Comment by danrot** [comment]
Changing the value of the dropdown field doesn't trigger the add button to get active.
