### PR TITLE
fixed block sorting for blocks with only one type

### LINKED ISSUE #1013: Block sort does not work smooth
SULU Version 0.16.1
If I try to sort blocks it works smooth if I move the block downwards - as soon as I want to move the block upwards it is extremely slow and doesn't work correctly anymore.

sulu-bug

### PR DESCRIPTION
**Pull request by danrot**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1013 
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/validation/types/block.js [hunk 1]
```diff
@@ -352,15 +352,6 @@ define([
                     }.bind(this));
                 },
 
-                checkSortable: function() {
-                    // check for dragable
-                    if (this.getChildren().length <= 1) {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/validation/types/block.js]: @wachterjohannes This method was not working correctly, since only the script tags used as block types have been loaded until here. So this statement was only true when more than two block types. I just removed it, and decided to make a div sortable as long as it has a maximum higher than 1.

Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/validation/types/block.js]: sounds reasonable!
