### PR TITLE
Fixed hreflang tag with only one language and different schemas

### LINKED ISSUE #2022: Incorrect hreflang implementation
Google writes following:

Google has detected that some pages on your site have implemented the rel-alternate-hreflang tag incorrectly. In particular, there seems to be a problem with incorrect language and region codes, or incorrect bi-directional linking (if page A links with hreflang to page B, there must be a link back from B to A as well). Google uses the hreflang attributes to serve the correct language or regional URL to the right users in search results.

In my case the problem seems to be the backlinking which is described above.

### LINKED ISSUE #2042: x-default set in sitemap.xml for one language
For websites based on one language no x-default should be set in the sitemap.xml.

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [x] test coverage

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #2022 fixes #2042
| Related PRs      | none 
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php [hunk 1]
```diff
@@ -73,10 +83,18 @@ public function renderSeoTags(array $seoExtension, array $content, array $urls,
             $webspaceKey = $webspace->getKey();
         }
 
+        $request = $this->requestStack->getCurrentRequest();
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php]: @webmozart WDYT about using the request like this in twig extensions? We need it to know if the links in this extension should be generated with `https://` or `http://`.

Comment (webmozart) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php]: Shouldn't be a problem as far as I can tell. But what about generating protocol relative URLs? (`//...`)

Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php]: After a very quick search I would conclude this is not a good idea:

* https://productforums.google.com/d/msg/webmaster-de/ZSyGtS6S938/Uhuyqh_RwsAJ
* http://www.paulirish.com/2010/the-protocol-relative-url/

The first link is about sitemaps, but I could imagine that google handles the links handled in this PR the same way.

So I think we should probably keep this way. Or maybe @c00n84 could drop some of this seo knowledge here :wink:

**Comment by wachterjohannes** [comment]
@danrot i have fixed the second issue as well now.

File: src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php (hunk 1 above)
Comment (webmozart) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php]: Interesting, thanks for those links!

**Comment by danrot** [comment]
@wachterjohannes Tests failing

File: src/Sulu/Component/Util/ArrayUtils.php [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+ */
+
+namespace Sulu\Component\Util;
+
+use Symfony\Component\ExpressionLanguage\ExpressionLanguage;
+
+/**
+ * Collection utilities working with symfony-expressions.
+ */
+final class ArrayUtils
```
Comment (danrot) [inline src/Sulu/Component/Util/ArrayUtils.php]: Would you really make that class final? And it would be nice to have this merged with `SortUtils`, but that's probably a BC break...

Comment (webmozart) [inline src/Sulu/Component/Util/ArrayUtils.php]: What's the point of extending it? I would also add a private constructor.

Comment (wachterjohannes) [inline src/Sulu/Component/Util/ArrayUtils.php]: +1 for private constructur. and +1 for merging but not in master i think (:

Comment (danrot) [inline src/Sulu/Component/Util/ArrayUtils.php]: @webmozart Actually the only reason for me would be to be consistent, since the `SortUtils` class is not final. Would probably be a good idea to do this as well. And private constructor definitely makes sense :-)

Comment (wachterjohannes) [inline src/Sulu/Component/Util/ArrayUtils.php]: hmm should i also make the sortutils final?

**Comment by danrot** [comment]
Isn't there a test missing for checking if the x-default is not set on a single language?

File: src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Sitemap/SitemapXMLGeneratorTest.php [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+        $content->setProperty('i18n:en_us-created', new \DateTime());
+        $content->setProperty('i18n:en_us-changer', 1);
+        $content->setProperty('i18n:en_us-changed', new \DateTime());
+        $content->setProperty('i18n:en_us-title', 'Homepage');
+        $content->setProperty('i18n:en_us-state', WorkflowStage::PUBLISHED);
+        $content->setProperty('i18n:en_us-published', new \DateTime());
+        $content->setProperty('i18n:en_us-url', '/');
+        $content->addMixin('sulu:home');
+
+        $webspace->addNode('temp');
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Sitemap/SitemapXMLGeneratorTest.php]: This node should not be added anymore.

Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Tests/Functional/Sitemap/SitemapXMLGeneratorTest.php]: fixed
