### PR TITLE
Removed automatic category translation

### LINKED ISSUE #1556: SQL Exception CategoryTranslation at Form flush
I have a form for the locale *de* and a shadow page *de_at* and *de_ch* with the shadowLocale *de*. Saving the form is working for *de* and *de_at*, but not for *de_ch* -> there's following error during flushing:

```
request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO ca_category_translations (translation, locale, idCategories) VALUES (?, ?, ?)' with params [null, "de_ch", 4]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translation' cannot be null" at /var/data/websites/www.candulor.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO ca_category_translations (translation, locale, idCategories) VALUES (?, ?, ?)' with params [null, \"de_ch\", 4]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translation' cannot be null at /var/data/websites/www.candulor.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translation' cannot be null at /var/data/websites/www.candulor.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'translation' cannot be null at /var/data/websites/www.candulor.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
```

Our temporary solution is to clear the entityManager before persisting and flushing my data.

We don't know why it want's to insert a new categoryTranslation but it seems like the error is from `Api/Category.php`
```
public function getTranslation()
    {
        foreach ($this->entity->getTranslations() as $translation) {
            if ($translation->getLocale() == $this->locale) {
                return $translation;
            }
        }
        $translation = new CategoryTranslation();
        $translation->setLocale($this->locale);
        $translation->setCategory($this->entity);

        $this->entity->addTranslation($translation);

        return $translation;
    }
```

If no translation exists, it creates a new one without a title.

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1556 
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/CategoryBundle/Api/Category.php [hunk 1]
```diff
@@ -348,6 +356,17 @@ public function getTranslation()
...
+
+        return;
+    }
+
+    /**
+     * Creates a new Translation for category.
+     *
+     * @return CategoryTranslation
+     */
+    public function createTranslation()
```
Comment (danrot) [inline src/Sulu/Bundle/CategoryBundle/Api/Category.php]: Would you make this method public? I think it should only be used inside this class.

Comment (wachterjohannes) [inline src/Sulu/Bundle/CategoryBundle/Api/Category.php]: hmm the `getTranslation` was public and not to make a to big BC we should also make this public ... i think!

Comment (danrot) [inline src/Sulu/Bundle/CategoryBundle/Api/Category.php]: Was it really used? I don't see any advantage in having this method public, since you still have to call `setName` afterwards, otherwise the insert will still fail. Then the UPGRADE file would simply change from change this line to omit this line. Don't think that this is a bigger BC break than the current one.

Comment (wachterjohannes) [inline src/Sulu/Bundle/CategoryBundle/Api/Category.php]: ok i will remove it!
