### PR TITLE
Fixed delete page which has children with history url

### LINKED ISSUE #868: Page cant be deleted when a page was moved with url history
1. I create the following structure
 - A
    - B
       - C
    - D

When I move B into D its not possible to delete D reference error with the old url history uuid.
You must delete B before you can delete D.

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [x] test coverage
- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #868
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Component/Content/Mapper/ContentMapper.php [hunk 1]
```diff
@@ -2015,6 +2015,10 @@ private function adaptResourceLocator(
      */
     private function deleteRecursively(NodeInterface $node, $webspace, $dereference = false)
     {
+        foreach ($node->getNodes() as $childNode) {
+            $this->deleteRecursively($childNode, $webspace, $dereference);
```
Comment (danrot) [inline src/Sulu/Component/Content/Mapper/ContentMapper.php]: Are you sure this is safe to be called recursively?

**Comment by dantleech** [comment]
This logic is no longer in the content mapper in the refactoring.

**Comment by dantleech** [comment]
And would it be better fixed in the next step of the refactoring? Where all `sulu:history` nodes reference the content (instead of the route node).

File: src/Sulu/Component/Content/Mapper/ContentMapper.php (hunk 1 above)
Comment (wachterjohannes) [inline src/Sulu/Component/Content/Mapper/ContentMapper.php]: yeah because down all content nods (childs) will be deleted, so all history nodes urls of the child should be deleted to!

**Comment by danrot** [comment]
We can't wait for every fix until the refactoring is done... But what we can maybe do is to move these tests to the node controller, so that it will be checked later again. /cc @wachterjohannes

**Comment by wachterjohannes** [comment]
@dantleech should we do this? cannot you run the content mapper test afterwards?

**Comment by dantleech** [comment]
The content mapper test has changed quite alot. But I will have to port the changes. It is ok as it is.

**Comment by wachterjohannes** [comment]
ok

File: tests/Sulu/Component/Content/Mapper/ContentMapperTest.php [hunk 2]
```diff
@@ -1479,17 +1479,17 @@ public function testDelete()
...
-            ->method('dispatch')
-            ->with(
-                $this->equalTo(ContentEvents::NODE_POST_DELETE),
-                $this->isInstanceOf('Sulu\Component\Content\Event\ContentNodeDeleteEvent')
-            );
+        ->method('dispatch')
+        ->with(
+            $this->equalTo(ContentEvents::NODE_POST_DELETE),
+            $this->isInstanceOf('Sulu\Component\Content\Event\ContentNodeDeleteEvent')
+        );
```
Comment (danrot) [inline tests/Sulu/Component/Content/Mapper/ContentMapperTest.php]: Looks like wrong indentations to me.

File: tests/Sulu/Component/Content/Mapper/ContentMapperTest.php [hunk 3]
```diff
@@ -1510,6 +1511,60 @@ public function testDelete()
...
+        // save content
+        $data[0] = $this->mapper->save($data[0], 'overview', 'default', 'de', 1);
+        $data[1] = $this->mapper->save($data[1], 'overview', 'default', 'de', 1, true, null, $data[0]->getUuid());
+        $data[2] = $this->mapper->save($data[2], 'overview', 'default', 'de', 1, true, null, $data[1]->getUuid());
+        $data[3] = $this->mapper->save($data[3], 'overview', 'default', 'de', 1, true, null, $data[0]->getUuid());
+
+        // move /a/b to /a/d/b
+        $this->mapper->move($data[1]->getUuid(), $data[3]->getUuid(), 1, 'default', 'de');
+
+        // delete /a/d/b
```
Comment (danrot) [inline tests/Sulu/Component/Content/Mapper/ContentMapperTest.php]: Actually /a/d should be deleted.
