### PR TITLE
Fixed dropdown of target locales

### LINKED ISSUE #2160: Custom URL overlay shows wrong localizations
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

The overlay for custom urls shows the default languages of Sulu, and not the ones available in the system.

image

As can be seen in the screenshot only the locales `de` and `en` are shown, although I have also defined `en_us` and `de_at`. Furthermore that enables 

#### Expected Behavior

I would expect that only the language in which the linked page exists are shown. This would also mean that the language can't be selected before the page has been selected

#### Steps to Reproduce

1. Navigate to `Webspaces -> settings``
2. Select the `Custom URL` tab
3. Click on the localization dropdown
4. Only two `en` and `de` are shown (even if the selected page does not exist in this language)

If a localization is selected in which the page has not been translated, the homepage is shown for this link.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #2160
| Related issues/PRs | https://github.com/massiveart/husky/pull/618
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR fixes the target-locale dropdown. After this the dropdown shows only concrete languages of the page.

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content-datasource/main.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ define([], function() {
                     selected: this.selected,
                     actionCallback: function(item) {
                         this.selected = item.id;
-                        this.options.selectCallback(item.id, item.path, item.title);
+                        this.options.selectCallback(item.id, item.path, item.title, item);
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content-datasource/main.js]: Is it really necessary to pass the entire item as the last parameter? If it is, would it be a too big BC break to remove the other three arguments?

Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Resources/public/js/components/content-datasource/main.js]: this compoenent was introduced for the smart-content. there yo have to pass the correct values for id, fullQualifiedName and title. otherwise you have to know which value you have to use in the smart-content

**Comment by danrot** [comment]
I get a javascript error and the overlay doesn't look too good:
image

**Comment by danrot** [comment]
The dropdown for the localizations should also be restricted by the localizations of the portal of the custom url. Otherwise errors like this can occur:

image

**Comment by wachterjohannes** [comment]
@danrot this should work now

File: src/Sulu/Bundle/CustomUrlBundle/Resources/public/js/components/webspace/settings/custom-url/overlay/main.js [hunk 2]
```diff
@@ -206,18 +206,30 @@ define(['underscore', 'text!./form.html'], function(_, form) {
          * Initializes sub-components.
          */
         initializeFormComponents: function() {
-            var routeData = _.filter(
-                _.map(this.data.routes, function(routeDocument, route) {
+            this.customUrls = {};
+
+            var unfilteredRouteData = _.map(this.data.routes, function(routeDocument, route) {
```
Comment (danrot) [inline src/Sulu/Bundle/CustomUrlBundle/Resources/public/js/components/webspace/settings/custom-url/overlay/main.js]: Why don't you use the [chain method of underscore](http://underscorejs.org/#chain) instead of introducing a variable which is not used afterwards?

Comment (wachterjohannes) [inline src/Sulu/Bundle/CustomUrlBundle/Resources/public/js/components/webspace/settings/custom-url/overlay/main.js]: @danrot fixed
