### PR TITLE
fixed displayOptions in media selection

### LINKED ISSUE #1430: Pages template media displayOptions false not considered
if you us set displayOptions to false they are rendered

This will not work:

``` xml
<param name="displayOptions" type="collection">
    <param name="leftTop" value="false"/>
    <param name="top" value="false"/>
    <param name="rightTop" value="false"/>
    <param name="left" value="false"/>
    <param name="middle" value="false"/>
    <param name="right" value="false"/>
    <param name="leftBottom" value="false"/>
    <param name="bottom" value="false"/>
    <param name="rightBottom" value="false"/>
</param>
```

This will work and no display Options will be rendered:
``` xml
<param name="displayOptions" type="collection">
</param>
```

### PR DESCRIPTION
**Pull request by danrot**
Booleans were not interpreted as booleans by the XmlLoader, this has been fixed.

__tasks:__

- [x] test coverage
- [x] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1430 
| BC breaks        | `"true"` and `"false"` are not interpreted as strings anymore
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php [hunk 1]
```diff
@@ -483,6 +472,14 @@ private function getValueFromXPath($path, \DOMXPath $xpath, \DomNode $context =
                 return $default;
             }
 
+            if ($item->nodeValue == 'true') {
```
Comment (chirimoya) [inline src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php]: `'true' === $item->nodeValue`

File: src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php [hunk 2]
```diff
@@ -483,6 +472,14 @@ private function getValueFromXPath($path, \DOMXPath $xpath, \DomNode $context =
...
+                return true;
+            }
+
+            if ($item->nodeValue == 'false') {
```
Comment (chirimoya) [inline src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php]: 'false' === $item->nodeValue
