### PR TITLE
Fixed URL Generation after copying language of a child node

### LINKED ISSUE #883: URL Generation after copying language for child node not working
**Language: DE**
*Parentnode:* test - URL: test
*Childnode:* childtest - URL: /test/childtest

**Language: EN**
After copying the Parentnode, I changed the title: **test-en** and URL: **test-en**
After copying the Childnode, the URL generation is wrong: **/test/childtest** instead of /test-en/childtest

### PR DESCRIPTION
**Pull request by wachterjohannes**
__Tasks:__

- [x] test coverage
- [ ] gather feedback for my changes
- [x] added changelog line

__Informations:__

| Q             | A
| ------------- | ---
| Tests pass?   | yes
| Fixed tickets | fixes #883
| BC Breaks     | none
| Doc           | none

### CODE REVIEW

File: src/Sulu/Component/Content/Mapper/ContentMapper.php [hunk 1]
```diff
@@ -1701,10 +1707,27 @@ public function copyLanguage(
...
         $data = $structure->toArray(true);
+        foreach ($destLanguageCodes as $destLanguageCode) {
+            if ($structure->hasTag('sulu.rlp')) {
+                $parentUrl = $resourceLocator->getResourceLocatorByUuid(
+                    $parentNode->getIdentifier(),
+                    $webspaceKey,
+                    $destLanguageCode
+                );
+                $rlp = $this->getResourceLocator()->getStrategy()->generate(
+                    $structure->getPropertyValue('title'),
```
Comment (dantleech) [inline src/Sulu/Component/Content/Mapper/ContentMapper.php]: Why do we not use the RLP of the source node instead of generating using the `title`?

File: tests/Sulu/Component/Content/Mapper/ContentMapperTest.php [hunk 2]
```diff
@@ -2299,6 +2299,60 @@ public function testMultipleLanguagesCopy()
...
+            null,
+            null,
+            false
+        );
+
+        $this->session->refresh(false);
+
+        $this->mapper->copyLanguage($data[1]->getUuid(), 1, 'default', 'de', 'en');
+
+
```
Comment (dantleech) [inline tests/Sulu/Component/Content/Mapper/ContentMapperTest.php]: Extra line

File: tests/Sulu/Component/Content/Mapper/ContentMapperTest.php [hunk 3]
```diff
@@ -2299,6 +2299,60 @@ public function testMultipleLanguagesCopy()
...
+            'overview',
+            'default',
+            'en',
+            1,
+            true,
+            $data[0]->getUuid(),
+            null,
+            null,
+            false
+        );
```
Comment (dantleech) [inline tests/Sulu/Component/Content/Mapper/ContentMapperTest.php]: Does this test cover two separate cases?

If so, it should be two separate test cases.

File: src/Sulu/Component/Content/Mapper/ContentMapper.php (hunk 1 above)
Comment (wachterjohannes) [inline src/Sulu/Component/Content/Mapper/ContentMapper.php]: because the "cached" is wrong at this place ... it should be recreated with the newest title and parent url for the new language!

File: tests/Sulu/Component/Content/Mapper/ContentMapperTest.php (hunk 3 above)
Comment (wachterjohannes) [inline tests/Sulu/Component/Content/Mapper/ContentMapperTest.php]: no it covers only one case ...

* copy language of parent
* change title of parent
* copy language of child 
* check new url of child

File: tests/Sulu/Component/Content/Mapper/ContentMapperTest.php (hunk 2 above)
Comment (wachterjohannes) [inline tests/Sulu/Component/Content/Mapper/ContentMapperTest.php]: fixed

**Comment by wachterjohannes** [comment]
@dantleech everything is fixed

**Comment by dantleech** [comment]
@wachterjohannes ok, needs a rebase and then you can merge

**Comment by dantleech** [comment]
Also should have been in the "review" queue :)
