### PR TITLE
Moved settings action to non-secured ProfileController

### LINKED ISSUE #645: user setting permission error 403
Since the permission is active for the `UserController`, the storage of user settings doesn't work for users without the appropriate permissions anymore. This action should not be secured at all, so it belongs to the `ProfileController`.

### PR DESCRIPTION
**Pull request by danrot**
The actions for defining user settings has been moved to the `ProfileController`, so that a user doesn't need the user-permission to change his own settings.

__tasks:__

- [x] test coverage
- [x] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #645 
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/public/js/aura_extensions/sulu-extension.js [hunk 1]
```diff
@@ -161,38 +161,28 @@
...
              * @param value
-             * @param url Defines where to save data to
              */
-            app.sandbox.sulu.saveUserSetting = function(key, value, url) {
+            app.sandbox.sulu.saveUserSetting = function(key, value) {
                 app.sandbox.sulu.userSettings[key] = value;
 
-                if (!url) {
-                    url = '/admin/api/users/' + SULU.user.id + '/settings/' + key;
-                }
```
Comment (danrot) [inline src/Sulu/Bundle/AdminBundle/Resources/public/js/aura_extensions/sulu-extension.js]: The `url`-parameter was never used, so I removed it (it also doesn't make any sense to me...)

File: src/Sulu/Bundle/AdminBundle/Resources/public/js/aura_extensions/sulu-extension.js [hunk 2]
```diff
@@ -161,38 +161,28 @@
...
                     type: 'PUT',
-                    url: url,
-                    data: data,
-                    processData: true,
-                    success: function(response) {
-
-                    }.bind(this),
-                    error: function(response) {
-                        app.sandbox.logger.log("error", response);
-                    }
```
Comment (danrot) [inline src/Sulu/Bundle/AdminBundle/Resources/public/js/aura_extensions/sulu-extension.js]: Removed the unused handlers. Also the error handler, since the browser shows failed requests anyway.

File: src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php [hunk 3]
```diff
@@ -10,20 +10,161 @@
...
+    }
+
+    /**
+     * Returns the settings for a key for the current user
+     *
+     * @param Request $request
+     *
+     * @return Response
+     */
+    public function getSettingsAction(Request $request)
```
Comment (danrot) [inline src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php]: @chirimoya @wachterjohannes @dantleech Can't find any usage of this action, if a user setting is set using the javascript extension it is set first on the client and then sent to the server, and loaded via the `SULU` javascript object over the controller which renders the index file.

Not sure if I should remove it, or leave it here just for completeness. Not saying what I would slightly prefer, since I want to hear your honest opinions :wink:

Comment (chirimoya) [inline src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php]: remove

Comment (wachterjohannes) [inline src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php]: remove it (=

**Comment by danrot** [comment]
Removed the action for getting a user setting, since it is not used. Should be ready to review/merge now.

**Comment by wachterjohannes** [comment]
@danrot looks good for me how can i test it?

File: src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php [hunk 4]
```diff
@@ -10,20 +10,128 @@
...
+     * Sets the given language on the current user
+     *
+     * @param Request $request
+     *
+     * @return Response
+     */
+    public function putLanguageAction(Request $request)
     {
-        $user = $this->getUser();
+        $user = $this->tokenStorage->getToken()->getUser();
```
Comment (dantleech) [inline src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php]: Can getToken return NULL?

File: src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php [hunk 5]
```diff
@@ -10,20 +10,128 @@
...
+            }
+
+            if (!$value) {
+                throw new MissingArgumentException(static::$entityNameUserSetting, 'value');
+            }
+
+            $user = $this->tokenStorage->getToken()->getUser();
+
+            // encode before persist
+            $data = json_encode($value);
```
Comment (dantleech) [inline src/Sulu/Bundle/SecurityBundle/Controller/ProfileController.php]: We would be better putting this into a UserSettingsManager I think.,

File: src/Sulu/Component/Security/Authentication/UserSettingRepositoryInterface.php [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+namespace Sulu\Component\Security\Authentication;
+
+use Doctrine\Common\Persistence\ObjectRepository;
+
+/**
+ * Describes how the user settings are retrieved from the database.
+ */
+interface UserSettingRepositoryInterface extends ObjectRepository
+{
+
```
Comment (dantleech) [inline src/Sulu/Component/Security/Authentication/UserSettingRepositoryInterface.php]: remove empty line
