### PR TITLE
Fixed alternate links with custom x-default locale and remove links to homepage

### LINKED ISSUE #1085: Meta hreflang x-default value should be configurable in webspace xml
Currently the x-default language is set from the default language of the webspace default language. That's not correct in every case. It should be able to configure the x-default language independently from the default language.

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [x] test coverage
- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1085
| BC breaks        | none
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/134

### CODE REVIEW

File: src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php [hunk 1]
```diff
@@ -168,16 +168,22 @@ private function renderAlternateLinks(array $urls, $webspaceKey)
...
-
-            $html .= $this->renderAlternateLink($urls[$defaultLocale], $webspaceKey, $defaultLocale, true);
+            $defaultLocale = $portal->getXDefaultLocalization()->getLocalization();
         }
 
         foreach ($urls as $locale => $url) {
-            $html .= $this->renderAlternateLink($url, $webspaceKey, $locale);
+            // url = '/' means that there is no translation for this page
+            // the only exception is the homepage where the requested resource-locator is false
+            if ($url !== '/' || $this->requestAnalyzer->getResourceLocator() === false) {
```
Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php]: Isn't there a cleaner way to do this? Would be better to not return these links at all, instead of integrating this strange check here?

Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php]: hmm the problem here is, that this urls array is used in different usages. one for locale chooser where you want this URLs and links to homepage for locales which are not exists ...

and the other way is here where you dont want this links to homepage ...

Comment (danrot) [inline src/Sulu/Bundle/WebsiteBundle/Twig/Seo/SeoTwigExtension.php]: Thinking of it, it would be nice if we wouldn't have to pass these arguments to the twig extension at all, but load them using injected services. Didn't think of that, when I refactored this part... Would be another BC break, so maybe a change for 2.0? /cc @chirimoya 

So I would say this is fine for now.
