### PR TITLE
Throw NoValidWebspaceException if no valid webspaces are found

### LINKED ISSUE #583: Better error handling when there is no valid webspace
Currently invalid webspaces are just skipped for fault-tolerance. However, if there is no valid webspace at all, there is a confusing error message:

```
InvalidArgumentException: Unknown portal environment "dev"
```

If there is no valid webspace at all, we should probably throw an better Exception, i.e. `NoValidWebspaceException`

### PR DESCRIPTION
**Pull request by patkar**
__Tasks:__

- [x] Add entry to `CHANGELOG.md`

__Informations:__

| Q             | A
| ------------- | ---
| Tests pass?   | yes
| Fixed tickets | fixes #583 
| BC Breaks     | no
| Doc           | none
| License | MIT

### CODE REVIEW

File: src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+ */
+
+namespace Sulu\Component\Webspace\Exception;
+
+/**
+ * Runtime exception if no valid webspaces are found
+ *
+ * @author Patrik Karisch <patrik@karisch.guru>
+ */
+class NoValidWebspaceException extends \RuntimeException
```
Comment (danrot) [inline src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php]: @patkar There is already a `WebspaceException` this one should extend.

File: src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php [hunk 2]
```diff
@@ -100,8 +101,8 @@ public function build()
         $this->portals = array();
         $this->portalInformations = array();
 
+        /** @var SplFileInfo $file */
```
Comment (danrot) [inline src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php]: @patkar Is there a reason you moved this to before the foreach?

Comment (patkar) [inline src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php]: The doc should be placed before the variable

File: src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php (hunk 1 above)
Comment (patkar) [inline src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php]: The inheritors of `WebspaceException` are supposed to have errors in webspaces. But in this case there is no valid webspace..

File: src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php (hunk 2 above)
Comment (danrot) [inline src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php]: I guess there are different opinions on that. I would prefer to keep this in the foreach, because it's always like that in the Sulu codebase, and if it is the first line in the foreach it is more clear that this is the loop variable.

Comment (patkar) [inline src/Sulu/Component/Webspace/Manager/WebspaceCollectionBuilder.php]: No problem to put it back. I've done it, because I've never seen it before this way and even PhpStorm puts the doc above the variable, if you issue `Alt + Enter -> Add PHPDoc comment` on the variable.

:smiley:

File: src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php (hunk 1 above)
Comment (danrot) [inline src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php]: Of course, you are right :smiley:

File: src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+ * This source file is subject to the MIT license that is bundled
+ * with this source code in the file LICENSE.
+ */
+
+namespace Sulu\Component\Webspace\Exception;
+
+/**
+ * Runtime exception if no valid webspaces are found
+ *
+ * @author Patrik Karisch <patrik@karisch.guru>
```
Comment (danrot) [inline src/Sulu/Component/Webspace/Exception/NoValidWebspaceException.php]: @patkar We decided not to do this, because it might change too often... And basically it's just duplicating the information we already have in git, so you are immortalized there :wink:

**Comment by danrot** [comment]
@patkar Please prefix the issues in the fixed tickets section with `fixes` in the future, so that the issue gets automatically closed.
