### PR TITLE
Fixed show ghost and shadow toggler in content column view

### LINKED ISSUE #1639: Property Type location won't open on 2nd edit
Hey Sulu Team,

If i use the property type location, i can set the informations in the edit overlay. If i click the ok-button, i can't open the overlay again and i have to reload the page to edit the informations.

Happend to me when using property type location in a block type and also when using it as normal property.

Sulu Version: dev-develop

### LINKED ISSUE #1640: Property Type category_list doesn't have the array-key "key" in preview
Hey Sulu Team,

just made a property with type category_list, on my page i loop through the category array and take their key. On my Page it works perfect, but in the Preview on Sulu an error occures:

Key "key" for array with keys "id, meta, creator, changer, created, changed" does not exist in ClientWebsiteBundle:templates:references.html.twig at line 21

Why is the preview showing this, but on my page it works like a charm?
Thanks for all your help :+1:

### LINKED ISSUE #1648: Show / Hide Shadowpage Button doesn't work like expected.
Never Hides Shadow page, maybe it occours with the other shadowpage bug.
https://github.com/sulu-io/sulu/issues/1647

bildschirmfoto 2015-10-01 um 11 11 37
bildschirmfoto 2015-10-01 um 11 11 29

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1648 , fixes #1640 , fixes #1639
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php [hunk 1]
```diff
@@ -635,15 +635,28 @@ public function getNodesTree(
...
      */
     private function loadNodeAndAncestors($uuid, $webspaceKey, $locale, $excludeGhost, $complete)
     {
-        $descendants = $this->getMapper()->loadNodeAndAncestors($uuid, $locale, $webspaceKey, $excludeGhost);
+        $descendants = $this->getMapper()->loadNodeAndAncestors(
+            $uuid,
+            $locale,
+            $webspaceKey,
+            $excludeGhost,
+            $excludeGhost
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php]: Do you really have to pass the same parameter twice?

File: src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php [hunk 2]
```diff
@@ -635,15 +635,28 @@ public function getNodesTree(
...
+        );
         $descendants = array_reverse($descendants);
 
         $childTiers = [];
         foreach ($descendants as $descendant) {
             foreach ($descendant->getChildren() as $child) {
+                $type = $child->getType();
+                if ($excludeGhost && $type !== null) {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php]: Why do you need that `$type` check?

File: src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php (hunk 1 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php]: yes ... but i could also introduce a new parameter for the controller (`$excludeShadow`) and pass this to this functions ...

File: src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php (hunk 2 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php]: because if the type is null its no ghost or shadow page!

File: src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php (hunk 1 above)
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php]: Yeah, I would do that, this looks very confusing to me...

File: src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php (hunk 2 above)
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Repository/NodeRepository.php]: Could you at least add a comment, describing that?

**Comment by wachterjohannes** [comment]
@danrot fixed

**Comment by danrot** [comment]
The categories are still not correctly working, the name is always missing, even if it is existent in the given locale.

**Comment by wachterjohannes** [comment]
@danrot fixed
