### PR TITLE
Fixed throw exception if new version has a different media type

### LINKED ISSUE #1889: Media type can change with a new file version
It is possible to add a new file version with an other media type than the old file version. Either this should not be possible or the media type should belong to the file version instead of the media.

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #1889
| Related issues/PRs | https://github.com/sulu-io/sulu-standard/pull/646
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR adding validation of the media type for new versions.

### CODE REVIEW

**Comment by danrot** [comment]
@wachterjohannes This PR has also conflicts keeping the tests from being executed.

File: src/Sulu/Bundle/MediaBundle/Resources/public/js/main.js [hunk 1]
```diff
@@ -103,11 +103,17 @@ define([
...
-                    var title = this.sandbox.translate('sulu.dropzone.error.title');
+                this.sandbox.on('husky.dropzone.error', function(xhr, file) {
+                    var title = this.sandbox.translate('sulu.dropzone.error.title'),
+                        message = 'sulu.dropzone.error.message';
+
                     title = title.replace('{{filename}}', this.sandbox.util.cropMiddle(file.name, 20));
 
-                    this.sandbox.emit('sulu.labels.error.show', 'sulu.dropzone.error.message', title);
+                    if(xhr.code === 5007){
+                        message ='sulu.dropzone.error.message.wrong-version';
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/main.js]: Shouldn't it be something like `wrong-filetype`?

**Comment by wachterjohannes** [comment]
@danrot fixed
