### PR TITLE
Fixed language chooser in collections

### LINKED ISSUE #960: Introduce the media edit language dropdown
when changing a media in overlay save all changed languages

### LINKED ISSUE #1120: Missing option to choose language in all media overview to search
bildschirmfoto 2015-05-22 um 09 03 49

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes
- [x] persist selected language
- [x] add language chooser to root collection
- [x] add language chooser to media edit
- [x] change detection overlay to save only if something has changed
- [x] after editing medias and close the overlay all items should be deselected
- [x] close button in multiple edit overlay

Related PRs:

* https://github.com/massiveart/husky/pull/487

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1120 , fixes #960
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

**Comment by wachterjohannes** [comment]
important test following:

* Change detection in media overlay (only save if something changed)
* When change the collection, the chosen language should be persisted

File: src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/content/main.js [hunk 1]
```diff
@@ -34,13 +34,15 @@ define(function() {
         /** returns normalized event names */
         createEventName = function(postFix) {
             return namespace + postFix;
-        };
+        },
+
+        MEDIA_LANGUAGE = 'mediaLanguage';
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/content/main.js]: Didn't we usually use a `constants`-variable for this kind of stuff? This way it could be easily confused with events.

Comment (wachterjohannes) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/content/main.js]: i have seen it like this way to but your right i will change it!

File: src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/media-edit/main.js [hunk 2]
```diff
@@ -129,25 +129,97 @@ define(function () {
...
+
+        /**
+         * Handles the changing of the language in the single-edit overlay
+         * @param locale
+         */
+        languageChangedSingle: function(locale) {
+            var id = this.media.id;
+
+            this.changeSingleModel();
+            this.sandbox.emit('sulu.media.collections.reload-single-media',
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/media-edit/main.js]: I would also move the event name into an own line.

File: src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/media-edit/main.js [hunk 3]
```diff
@@ -129,25 +129,97 @@ define(function () {
...
+
+        /**
+         * Handles the changing of the language in the singleedit overlay
+         * @param locale
+         */
+        languageChangedMultiple: function(locale) {
+            var medias = this.medias;
+            this.changeMultipleModel();
+
+            this.sandbox.emit('sulu.media.collections.reload-media',
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/media-edit/main.js]: Same as above.

File: src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/media-edit/main.js [hunk 4]
```diff
@@ -421,14 +508,20 @@ define(function () {
          * Maps the overlay input back on multiple models
          * @returns {Boolean} returns false if form is invalid, true if valid
          */
-        changeMultipleModel: function () {
+        changeMultipleModel: function() {
             if (this.sandbox.form.validate(constants.multipleEditFormSelector)) {
-                var data = this.sandbox.form.getData(constants.multipleEditFormSelector);
+                var data = this.sandbox.form.getData(constants.multipleEditFormSelector),
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/media-edit/main.js]: Is this the only difference to the function `changeSingleModel`? The this could be solved in a more elegant way.

Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/media-edit/main.js]: Forget about it...

File: src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/root/main.js [hunk 5]
```diff
@@ -40,15 +40,30 @@ define(['sulumedia/model/media'], function(Media) {
                     selectable: false
                 }
             }
-        };
+        },
+
+        MEDIA_LANGUAGE = 'mediaLanguage';
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/root/main.js]: Same as above, would place that in a constants variable, otherwise it could be confused with an event.

File: src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/root/main.js [hunk 6]
```diff
@@ -177,7 +195,7 @@ define(['sulumedia/model/media'], function(Media) {
                 },
                 {
                     el: this.$find(constants.datagridSelector),
-                    url: '/admin/api/media?orderBy=media.changed&orderSort=DESC',
+                    url: '/admin/api/media?orderBy=media.changed&orderSort=DESC&locale=' + this.locale,
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/root/main.js]: Not related to your PR, but maybe you can fix it also: I think we always write `desc` in lowercase, don't we?

Comment (wachterjohannes) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/root/main.js]: the language chooser in the "root" is also new! this was one of the two issues which i fix with this PR. i will change the DESC to desc!

**Comment by wachterjohannes** [comment]
@danrot fixed everything

File: src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/root/main.js (hunk 6 above)
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/root/main.js]: As said, it's not really your issue, just asked you to change it, if you already have changed this line anyway :smiley:

Comment (wachterjohannes) [inline src/Sulu/Bundle/MediaBundle/Resources/public/js/components/collections/components/root/main.js]: ah ok i have misunderstand your comment (= no problem :+1:
