### PR TITLE
Fixed UI breakpoints for sidebar

### LINKED ISSUE #1604: inconsistent 3-column layout styling
the responsive styling of the main three-column-layout causes different problems when a sidebar is shown. (see https://github.com/sulu-io/sulu/issues/1579).

we need to adapt the layout.scss of the adminbundle to fix this.

as the content-column should have a width of 920px to prevent overflow, there should be three states when a sidebar is shown:
*viewport width < 1270*:                 navigation collapsed (50px), sidebar hidden
*1420 <= viewport width < 1620*:   navigation collapsed (50px), sidebar shown (450px)
*1620 <= viewport width*:               navigation uncollapsed (250px), sidebar shown (450px)

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__Related PR:__

* https://github.com/massiveart/husky/pull/551 (fixes category view part of issue #1579 )
* https://github.com/sulu-io/SuluContactExtensionBundle/pull/28

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1604 , fixes parts of #1579
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/AdminBundle/Resources/public/js/components/header/main.js [hunk 1]
```diff
@@ -596,6 +596,9 @@ define([], function() {
                     }
                 }.bind(this));
             } else {
+                // if no component is set render title
+                this.renderTitle();
```
Comment (danrot) [inline src/Sulu/Bundle/AdminBundle/Resources/public/js/components/header/main.js]: What is this about?

File: src/Sulu/Bundle/AdminBundle/Resources/public/scss/variables.scss [hunk 2]
```diff
@@ -21,7 +21,7 @@ $contentFixedWidth: 920px;
 $maxContentMinWidth: 610px;
 $contentMinWidth: 510px;
 $contentFixedMediumWidth: 700px;
```
Comment (danrot) [inline src/Sulu/Bundle/AdminBundle/Resources/public/scss/variables.scss]: I guess this variable is not used anymore?
