### PR TITLE
Fixed translator locale for preview

### LINKED ISSUE #1280: Preview shows wrong translation
On a project with multiple languages I've added a translation file for each language in following directory `ClientWebsiteBundle/Resources/translations` named `messages.de.xliff` and `messages.en.xliff`. 

The translations are working in the frontend when I call them in a twig template with `{{ translate_key|trans }}`. Like documented here: http://symfony.com/doc/current/book/translation.html

The problem is, that the translations are *wrong in the preview* - it seems to display the translation of the default language.

Tested in multiple project - this bug seems to exists since RC1 or earlier.

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1280 
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Preview/PreviewRenderer.php [hunk 1]
```diff
@@ -69,14 +76,21 @@ public function render(PageBridge $content, $partial = false)
...
+        $localeBefore = $this->translator->getLocale();
+        $this->translator->setLocale($content->getLanguageCode());
+
         $this->requestStack->push($request);
         /** @var Response $response */
         $response = $controller[0]->{$controller[1]}($content, true, $partial);
+
+        // roll back
         $this->requestStack->pop();
+        $this->translator->setLocale($localeBefore);
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Preview/PreviewRenderer.php]: Just curious: for what do we need the rollback?

Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Preview/PreviewRenderer.php]: i dont know what happens after this! so i roll back to the previous state ...

File: src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/PreviewRendererTest.php [hunk 2]
```diff
@@ -87,7 +91,7 @@ function ($request) {
         $requestStack->expects($this->once())
             ->method('pop');
 
-        $renderer = new PreviewRenderer($activeTheme, $controllerResolver, $webspaceManager, $requestStack);
+        $renderer = new PreviewRenderer($activeTheme, $controllerResolver, $webspaceManager, $requestStack, $translator);
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Tests/Unit/Content/PreviewRendererTest.php]: You could test here if the locale of the translator is really set.
