### PR TITLE
Fixed error for cacheLifetime is "0"

### LINKED ISSUE #1385: Error if cacheLifetime of template is set to 0
Error: Property "cacheLifetime" is required in XML template file "/var/data/websites/domain.lo/app/Resources/pages/form.xml"

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixed #1385
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php [hunk 1]
```diff
@@ -137,12 +137,21 @@ private function loadTemplateAttributes($resource, \DOMXPath $xpath, $type)
...
                 'meta' => $this->loadMeta('/x:template/x:meta/x:*', $xpath),
             );
 
-            $result = array_filter($result);
+            $result = array_filter(
+                $result,
+                function ($value) {
+                    if (is_array($value)) {
+                        return $value != null;
+                    }
```
Comment (danrot) [inline src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php]: This check is really confusing... I guess you also want to check if the array is empty. Isn't it possible to just use `$value != null` for the entire callback? Or to use `empty()`? And to write that in a single line?

Comment (wachterjohannes) [inline src/Sulu/Component/Content/Metadata/Loader/XmlLegacyLoader.php]: @danrot i do `$value !== null` and add the empty arrays to the testcase ... so it is fixed!

**Comment by wachterjohannes** [comment]
@danrot fixed everything
