### PR TITLE
Fixed maximum file size of dropzone

### LINKED ISSUE #832: File upload have a 256MB frontend limit with no error message
The used JS library dropzone currently have a default limit from 256MB.
When possible this should be configurateable, also currently no error message is shown when you want to upload a file over 256MB.
- https://github.com/enyo/dropzone/wiki/FAQ

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__Related PRs:__

* https://github.com/sulu-io/sulu-standard/pull/533
* https://github.com/massiveart/husky/pull/567

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixed #832 
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -54,6 +54,15 @@ public function getConfigTreeBuilder()
                     ->end()
                 ->end()
             ->end()
+            ->arrayNode('dropzone')
```
Comment (danrot) [inline src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php]: Would you really put dropzone here? Can't we call it upload or something, who knows which other ways we will offer in the future.

Comment (wachterjohannes) [inline src/Sulu/Bundle/MediaBundle/DependencyInjection/Configuration.php]: no problem

**Comment by wachterjohannes** [comment]
@danrot fixed
