### PR TITLE
Fixed preview renderer exception handling

### LINKED ISSUE #720: Error message: public.server_error 200
The javascript which parses the 500 exceptions from the backoffice does not deal with HTML exceptions properly, causing this error.

### PR DESCRIPTION
**Pull request by wachterjohannes**
fixes #720

__tasks:__

- [x] test coverage
- [ ] gather feedback for my changes
- [x] Preview renderer exception handling
- [x] Log message for render bug with additional information
- [x] Remove global error handler except 401, 403

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #720
| BC breaks        |none
| Documentation PR | none

### CODE REVIEW

File: src/Sulu/Bundle/ContentBundle/Preview/PreviewException.php [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+     * PreviewException constructor.
+     *
+     * @param string $message
+     * @param int $code
+     * @param \Exception $previous
+     */
+    public function __construct($message = '', $code = 0, \Exception $previous = null)
+    {
+        parent::__construct($message, $code, $previous);
+    }
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Preview/PreviewException.php]: I would not override the constructor if you just call the parent constructor with the same arguments.

File: src/Sulu/Bundle/ContentBundle/Preview/Preview.php [hunk 2]
```diff
@@ -142,8 +142,13 @@ public function updateProperty($userId, $contentUuid, $webspaceKey, $locale, $pr
             throw new PreviewNotFoundException($userId, $contentUuid);
         }
 
-        $content = $this->update($userId, $webspaceKey, $locale, $property, $data, $content);
-        $this->previewCache->saveStructure($content, $userId, $contentUuid, $webspaceKey, $locale);
+        try {
+            $content = $this->update($userId, $webspaceKey, $locale, $property, $data, $content);
+        } catch (\Twig_Error $ex) {
+            throw new TwigPreviewException($ex);
+        } finally {
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Preview/Preview.php]: Does this really make sense? Can you save something in the cache even if there has been a failure?

File: src/Sulu/Bundle/ContentBundle/Preview/TwigPreviewException.php [hunk 3]
```diff
@@ -0,0 +1,26 @@
+<?php
+
```
Comment (danrot) [inline src/Sulu/Bundle/ContentBundle/Preview/TwigPreviewException.php]: missing header

File: src/Sulu/Bundle/WebsocketBundle/Resources/public/js/component/websocket-manager/client/ajax.js [hunk 4]
```diff
@@ -36,7 +36,12 @@ define(['websocket/abstract', 'jquery'], function(Client, $) {
             data: {message: this.generateMessage(handler, message, {})}
         }).then(function(data) {
             this._onMessage.notify(data);
-            def.resolve(data.handler, data.message);
+
+            if (!data.error) {
```
Comment (danrot) [inline src/Sulu/Bundle/WebsocketBundle/Resources/public/js/component/websocket-manager/client/ajax.js]: What's `data.error`? What is the structure of this `data`-array anyway?

File: tests/Sulu/Component/Websocket/MessageDispatcher/MessageDispatcherTest.php [hunk 5]
```diff
@@ -82,7 +83,50 @@ public function testDispatchNonResult()
...
+    public function testDispatchMessageHandlerException()
+    {
+        $context = $this->prophesize('Sulu\Component\Websocket\MessageDispatcher\MessageHandlerContext');
+        $conn = $this->prophesize('Ratchet\ConnectionInterface');
+        $message = array('test' => '1');
+
+        $ex = new \Exception('Thats my message', 4211);
+
+        $handler = $this->prophesize('Sulu\Component\Websocket\MessageDispatcher\MessageHandlerInterface');
+        $handler->handle($conn->reveal(), $message, $context->reveal())->wilLThrow(new MessageHandlerException($ex));
```
Comment (danrot) [inline tests/Sulu/Component/Websocket/MessageDispatcher/MessageDispatcherTest.php]: `willThrow` instead of `wilLThrow`

File: src/Sulu/Bundle/WebsocketBundle/Resources/public/js/component/websocket-manager/client/ajax.js (hunk 4 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/WebsocketBundle/Resources/public/js/component/websocket-manager/client/ajax.js]: you get following informations:

```php
        return array(
            'handler' => $name,
            'message' => $message,
            'options' => $options,
            'error' => $error
        );
```

* `handler`: requested handler
* `message`: result of handler
* `options`: requested options
* `error`: flag which indicates if there was an error or not

File: src/Sulu/Bundle/ContentBundle/Preview/Preview.php (hunk 2 above)
Comment (wachterjohannes) [inline src/Sulu/Bundle/ContentBundle/Preview/Preview.php]: yes because you also should store the data if a rendering error occurs!

**Comment by danrot** [comment]
@wachterjohannes That doesn't look like it is intended:
image

**Comment by wachterjohannes** [comment]
@chirimoya i have fixed @danrot comments you can merge it, if it is green.

**Comment by danrot** [comment]
There's an odd difference in behavior between the websocket and ajax preview. If you get a twig error because you use a variable which is not in the current block as described in #720 you get the twig error returned and the preview is not updated. In the websocket mode it just works, although it should fail the same way.
